### ISSUE TITLE
Create all Github actions workflows needed

### ISSUE THREAD

**Issue by ixahmedxi** [ixahmedxi/orbitkit#12]
OrbitKit needs to also deliver github actions as part of the starterkit to help people have a solid foundation where their work is tested and checked, I have a few ideas for the kind of actions we need but here's what my mind thinks:

- Obviously the normal lint, typecheck, build, checks (turborepo)
- We need to do it so that a Neon DB branch is created for every new Pull Request, which gets consumed by the actions of that pull request and when the pull request is closed or merged, we need to run an action that will destroy that branch.
- We also need the github action to integrate with chromatic/storybook and mintlify
- I am not sure if we will need to handle vercel deployment from the github actions, because I was thinking it would actually maybe be a good idea for every pull request to have two db branches on neon, one is used for the github actions to run the e2e tests on top...etc and another one is created from the neon vercel integration for the preview deployment that way you don't get e2e test specific data into your preview deployment, further increasing accuracy between both preview and production deployment.
- We can put in templates for slack/discord messaging through the github actions maybe.

Would love to hear more thoughts about this as that I'm not the most knowledgable person when it comes to github actions.

**Comment by xMohamd** [comment]
More details? What kind of actions do you need?

**Comment by ixahmedxi** [comment]
> More details? What kind of actions do you need?

Hello @xMohamd sorry I have now updated the description of this issue to reflect more about what I mean. Thank you!

**Comment by raoufchebri** [comment]
Hey @ixahmedxi, are you thinking of using Neon GitHub Actions to create and delete branches?
https://github.com/marketplace/actions/neon-database-create-branch-action
https://github.com/marketplace/actions/neon-database-delete-branch

**Comment by ixahmedxi** [comment]
> Hey @ixahmedxi, are you thinking of using Neon GitHub Actions to create and delete branches?
> 
> https://github.com/marketplace/actions/neon-database-create-branch-action
> 
> https://github.com/marketplace/actions/neon-database-delete-branch

Hey @raoufchebri yes that is exactly correct, I was actually looking at it a while ago and it seemed like a perfect fit for this purpose.
