### ISSUE TITLE
create a `packages/hooks` package

### ISSUE THREAD

**Issue by ixahmedxi** [ixahmedxi/orbitkit#22]

**Comment by imCorfitz** [comment]
As in React hooks? Something a la [usehooks](https://usehooks-ts.com/introduction)?

**Comment by ixahmedxi** [comment]
Yeah basically something like that, where the user of the starterkit can define their custom hooks and be able to re-use them across the monorepo the same way we have the ui package currently.

**Comment by ixahmedxi** [comment]
Closing this because I think a package like `usehooks-ts` does 95% of most use cases and the other times the user should be able to create their own `hooks` package and add their custom hooks in it.
