### ISSUE TITLE
Env with a 3rd party

### ISSUE THREAD

**Issue by Mahmoudgalalz** [ixahmedxi/orbitkit#31]
Right now you might need to share envs with all these mono-repos

I highly recommend to use a 3rd party app that manage this, and it has CLI for that too.

https://onboardbase.com

**Comment by ixahmedxi** [comment]
I don't think we should actually do this because that is something each company has to decide for themselves when it comes to secrets management, we just tell them what secrets the app needs to run and they should figure out if they wanna use Doppler, Onboardbase, dotenv-vault or whatever.
