### ISSUE TITLE
Add security advisory to repo

### ISSUE THREAD

**Issue by imCorfitz** [ixahmedxi/orbitkit#33]
**Describe the bug**
To report a security issue, we currently direct users to a 404 page.

**To Reproduce**
Click the [open a security advisory](https://github.com/ixahmedxi/orbitkit/security/advisories/new) link in SECURITY.md. 

**Expected behavior**
The ability to report a security vulnearbility.

**Additional context**
Follow these docs: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/creating-a-repository-security-advisory#creating-a-security-advisory

**Comment by ixahmedxi** [comment]
I can actually see it...it doesn't give me a 404 page.

**Comment by imCorfitz** [comment]
Might be because you are admin.

**Comment by xMohamd** [comment]
@ixahmedxi Corfitz is right. It's giving me a 404 error.

**Comment by ixahmedxi** [comment]
It looks like it's something I haven't enabled then...

**Comment by ixahmedxi** [comment]
I basically have everything in the security overview list enabled hmm

**Comment by xMohamd** [comment]
It's work now. Great work.
![image](https://github.com/ixahmedxi/orbitkit/assets/10786768/5ec446cd-c47d-4df5-be8b-1bca408497c2)
