### ISSUE TITLE
Migrate to v9 of ESLint and flat config

### ISSUE THREAD

**Issue by ixahmedxi** [ixahmedxi/orbitkit#35]
With the release of ESLint v9, we will need to move `packages/config/eslint` to flat config style configuration and also remove all `.eslintrc.cjs` files and replace them with the modern counterparts.

The only hurdle I see to this being successful is `eslint-config-next` but honestly I am tempted to remove it because a lot of the useful rules aren't even working anymore, and that way the react config can be both react in general specific so we don't have a next.js and a react specific eslint configs.

https://github.com/antfu/eslint-config should be a big inspiration for this migration, not the formatting with ESLint part because we use prettier for that but the code organisation and config of that package is absolute awesome and we should learn from this and implement our new version with this as the inspiration.

**Comment by duttaoindril** [comment]
I'd say remove it

**Comment by ixahmedxi** [comment]
Done
