### ISSUE TITLE
How to use the icons?

### ISSUE THREAD

**Issue by yimity** [ixahmedxi/orbitkit#53]
**Describe the bug**
The icons repository was installed from '@radix-ui/react-icons', but it is not exported from the UI packages and not installed for the web. Should the user add it to the web or export it from the UI directory?

Thank you for your advice.

**Comment by ixahmedxi** [comment]
If you need it in the web app, you should just install it like so: `pnpm --filter web add @radix-ui/react-icons`.

**Comment by yimity** [comment]
> If you need it in the web app, you should just install it like so: `pnpm --filter web add @radix-ui/react-icons`.

I got it. Thank you so much.
