### ISSUE TITLE
Backend support

### ISSUE THREAD

**Issue by jorgeorejas** [ixahmedxi/orbitkit#54]
**Is your feature request related to a problem? Please describe.**
I'm developing an application that require both Cron Jobs and Queues

**Describe the solution you'd like**
Have a backend, it could be simple, something like [Bull](https://github.com/OptimalBits/bull) as an example.

**Describe alternatives you've considered**
There is also the option to use Agenda that uses Mongo

**Additional context**
Bull is a simple to use queue and cron job managing system that uses Redis as it's database

**Comment by ixahmedxi** [comment]
Wouldn't something like https://vercel.com/blog/cron-jobs be sufficient here?

**Comment by jorgeorejas** [comment]
Tbh, I think it would do the trick! 

Thanks!
