### ISSUE TITLE
Feature Request: bulk rename package namespaces

### ISSUE THREAD

**Issue by tconroy** [ixahmedxi/orbitkit#63]
**Is your feature request related to a problem? Please describe.**
During project setup, it'd be nice to be able to bulk-rename all the package namespaces from `@orbitkit/*` to `@<some custom namespace>/*`

**Describe the solution you'd like**
Ideal solution would either be a setup script during initial clone/bootstrap, along with a `rename` script within the top-level package.json to allow re-running renames in the future.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ixahmedxi** [comment]
That is actually something I have been thinking about recently, probably going to end up providing a setup script that:
1. renames all packages and references of "orbitkit" to your input.
2. nukes itself after you run it.

**Comment by tconroy** [comment]
Hi @ixahmedxi! That sounds like a great solution. I like the addition of a nuke/cleanup after it's run 👍

**Comment by ixahmedxi** [comment]
This is not done via the `bun update:workspace` command available to you from the root package.json file.
