### ISSUE TITLE
I'm not able to build the project locally, even after following the steps in the contributing file.

### ISSUE THREAD

**Issue by 0xmbadr** [ixahmedxi/orbitkit#78]
**Describe the bug**
I am trying to run the template locally. however, after creating `.env.local` in `apps/web` and running `bun turbo build` an issue of `Invalid environment variables` has shown up. 

Apparently,`DATABASE_URL` is not accessible during executing `drizzle-kit generate` command.

**To Reproduce**

1. clone the project into a directory of choice.
2. run `bun install`
3. create `.env.local` in `apps/web` and fill it (make sure to fill all required variables, especially `DATABASE_URL`)
4. run `bun turbo build`

**Expected behavior**
The project should be successfully built.

**Additional context**
```bash
@orbitkit/db#db:generate > cache miss, executing 7252559029528ce2 
│ $ drizzle-kit generate
│ drizzle-kit: v0.22.7
│ drizzle-orm: v0.31.2
│ 
│ No config path provided, using default 'drizzle.config.ts'
│ Reading config file '/home/badr/../orbitkit/packages/db/drizzle.config.ts'
│ ❌ Invalid environment variables: { DATABASE_URL: [ 'Required' ] }
│ /home/badr/.../orbitkit/node_modules/@t3-oss/env-core/dist/index.js:29
│         throw new Error("Invalid environment variables");
...
│ Node.js v21.5.0
│ error: script "db:generate" exited with code 1
│ command finished with error: command (/home/badr/.../orbitkit/packages/db) /home/badr/.bun/bin/bun run db
│ :generate exited (1)

...

ERROR  run failed: command  exited (1)
error: "turbo" exited with code 1
```

**Comment by imCorfitz** [comment]
Did you symlink the env file as per the documentation? https://orbitkit.dev/installation#configuring-environment-variables

**Comment by 0xmbadr** [comment]
I didn't. This apparently solves it. Thank you.
